In [3]:
import numpy as np

1. Methemetical Operation

In [5]:
print("1. Methemetical Operation")

a = np.array([
    [10 , 20 , 30],
    [40 , 50 , 60],
    [70 , 80 , 90]
])

b = np.array([
    [1 , 2 , 3],
    [4 , 5 , 6],
    [7 , 8 , 9]
])

print("Array A:")
print(a)

print("Array B:")
print(b)

print("Addition:")
print(a + b)

print("Subtraction:")
print(a - b)

print("Multiplication:")
print(a * b)

print("Division:")
print(a / b)

1. Methemetical Operation
Array A:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Array B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Addition:
[[11 22 33]
 [44 55 66]
 [77 88 99]]
Subtraction:
[[ 9 18 27]
 [36 45 54]
 [63 72 81]]
Multiplication:
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
Division:
[[10. 10. 10.]
 [10. 10. 10.]
 [10. 10. 10.]]


2. Square Root , Expontial and Logarithmic Function

In [6]:
print("square Root , Expontial and Logarithmic Function")

arr = np.array([1 , 2 , 3 , 4 , 5])

print("Square Root : ")
#print(np.sqrt(arr))

print("Expontial :")
print(np.exp(arr))
print(arr)

print("Natural Logarithmic :")
print(np.log(arr))

print("Base 10 Logarithmic :")
print(np.log10(arr))

square Root , Expontial and Logarithmic Function
Square Root : 
Expontial :
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[1 2 3 4 5]
Natural Logarithmic :
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
Base 10 Logarithmic :
[0.         0.30103    0.47712125 0.60205999 0.69897   ]


3. Trigonometric Operations

In [7]:
print("Trigonometric Operations")

angle = np.array([0 , 30 , 45 , 60 , 90])

radians = np.deg2rad(angle)

print(np.sin(radians))
print(np.cos(radians))
print(np.tan(radians))

Trigonometric Operations
[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


4. Normalize an Array

Formula: (value-mean) / standard deviation

In [8]:
data = np.array([10 , 20 , 30 , 40 , 50])

std = np.std(data)
mean = np.mean(data)

normalize = (data-mean) / std

print(data)

print(mean)

print(std)

print(normalize)

[10 20 30 40 50]
30.0
14.142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
