In [1]:
import numpy as np


#### 2. Combining and Splitting Arraya

In [2]:
print("Horizontal and Vertical Concatination")

arr1 = np.array([1 , 2 , 3])
arr2 = np.array([4 , 5 , 6])

print(arr1)
print(arr2)

horizontal = np.hstack((arr1, arr2))

vertical = np.vstack((arr1, arr2))

print(horizontal)
print(vertical)

Horizontal and Vertical Concatination
[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


#### # vstack , hstack and Split vsplit and hsplit

#### Double - click (or enter) to edit

In [3]:
print("Stack and Split Arrays")

arr1 = np.array([
    [1 , 2],
    [3 , 4],
    [5 , 6]
])


arr2 = np.array([
    [7 , 8 , 9 , 10 , 11 , 12],
    [13 , 14 , 15 , 16 , 17 , 18]
])

print(arr1)
print(arr2)

#v_stack = np.vstack((arr1 , arr2))

#h_stack = np.hstack((arr1 ,arr2))

#print(v_stack)

#print(h_stack)

#v_split = np.vsplit(v_stack , 3)

h_split = np.hsplit(arr2 , 6)

#print(v_split)

print(h_split)



Stack and Split Arrays
[[1 2]
 [3 4]
 [5 6]]
[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[array([[ 7],
       [13]]), array([[ 8],
       [14]]), array([[ 9],
       [15]]), array([[10],
       [16]]), array([[11],
       [17]]), array([[12],
       [18]])]


#### # Flattern and reshape 3D Array

In [ ]:
print("Flattern and Reshape 3D Arrays")

arr_3d = np.array([
    [[1 , 2] , [3 , 4]],
    [[5 , 6] , [7 , 8]]
])

print(arr_3d)

print(arr_3d.shape)

flat_arr